# Generated by Django 5.1.7 on 2025-03-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=50)),
                ('passwd', models.CharField(max_length=50)),
            ],
        ),
    ]
